package com.campussocialmedia.campussocialmedia.entity;

import java.util.Date;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

//CONFIRMATIONTOKEN TABLE
@DynamoDBTable(tableName = "ConfirmationToken")
public class ConfirmationToken {
	
	private String tokenid;
    private String confirmationToken;
    private Date createdDate;
    private String username;

    
    
    public ConfirmationToken() {
		super();
	}

	public ConfirmationToken(String username) {
        this.username = username;
        createdDate = new Date();
        confirmationToken = UUID.randomUUID().toString();
    }

    
	@DynamoDBAttribute
	@DynamoDBAutoGeneratedKey
	public String getTokenid() {
		return tokenid;
	}

	public void setTokenid(String tokenid) {
		this.tokenid = tokenid;
	}

	@DynamoDBHashKey(attributeName = "confirmationToken")
	public String getConfirmationToken() {
		return confirmationToken;
	}

	public void setConfirmationToken(String confirmationToken) {
		this.confirmationToken = confirmationToken;
	}

	@DynamoDBAttribute
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@DynamoDBAttribute
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
