# This is a basic workflow to help you get started with Actions

name: Jar Action

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to container registry
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU__API}}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU__API}}
      run: heroku container:push -a campus-social-media-backend web
    - name: Deploy
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU__API}}
      run: heroku container:release -a campus-social-media-backend web
