# This is a basic workflow to help you get started with Actions

name: Jar Action

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
      
    - uses: actions/checkout@v2
    - run: mkdir -p target/

    - run: echo hello > target/campus-social-media-0.0.1-SNAPSHOT.jar

    - uses: actions/upload-artifact@v1
      with:
       name: campus-social-media-0.0.1-SNAPSHOT
       path: target/
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
          name: campus-social-media-0.0.1-SNAPSHOT
          path: target/

    - run: cat target/campus-social-media-0.0.1-SNAPSHOT.jar
    - run: cd target && ls -C
#     - uses: actions/checkout@v2
#     - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
#       with:
#         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#         heroku_app_name: "campus-social-media-backend" #Must be unique in Heroku
#         heroku_email: "satvik.dandale@gmail.com"
#         usedocker: true
		
    
